package org.toldo;

import com.github.cage.Cage;
import com.github.cage.GCage;
import java.awt.image.BufferedImage;
import java.lang.reflect.InvocationTargetException;
import javax.swing.ImageIcon;
import com.omt.clipboard.main.ClipboardImage;
import java.awt.Toolkit;

/**
 * @author Luca Toldo
 */
public class Cagele extends java.applet.Applet {

    @Override
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                @Override
                public void run() {
                    initComponents();
                }
            });
        } catch (InterruptedException | InvocationTargetException ex) {
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("Capchit !");
        jButton1.setToolTipText("Click here to generate a capcha");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jSplitPane1.setLeftComponent(jButton1);

        jTextField2.setToolTipText("text (spaces not allowed) to be captched");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jSplitPane1.setRightComponent(jTextField2);

        add(jSplitPane1, java.awt.BorderLayout.NORTH);

        jLabel2.setToolTipText("here is shown the capcha");
        add(jLabel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        doit();
    }//GEN-LAST:event_jButton1MouseClicked

    private void doit() {
        String in = jTextField2.getText().replace(" ", "");
        jTextField2.setText(in);
        Cage cage = new GCage();
        BufferedImage bi = cage.drawImage(in);
        jLabel2.setIcon(new ImageIcon(bi));
        revalidate();
        repaint();
        // and now place the image in the system clipboard !
        clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        ClipboardImage clipboardImage = new ClipboardImage(bi);
        clipboard.setContents(clipboardImage,clipboardImage);
    }
    
    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
if(evt.getKeyCode() == 10)
		{
        doit();
		}

    }//GEN-LAST:event_jTextField2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JFormattedTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    private java.awt.datatransfer.Clipboard clipboard;
    
}
